twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_return
        timeout : 0.5
        priority: 10

      tracker:
        topic   : cmd_vel_tracking
        timeout : 0.5
        priority: 20

      joystick:
        topic   : cmd_vel_joy
        timeout : 2.0
        priority: 100